filters:
  - filter_type: file
    # all supported i18n types: https://docs.transifex.com/formats
    file_format: PO
    source_language: en
    source_file: aa_forum/locale/en/LC_MESSAGES/django.po
    # path expression to translation files, must contain <lang> placeholder
    translation_files_expression: 'aa_forum/locale/<lang>/LC_MESSAGES/django.po'
